### ISSUE TITLE
✏️ Create show card to 'list' style component

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#289]
Refactor the show card to resemble a list more than a gallery of cards. It may make more sense for this to be a new component in case we want to use the current card elsewhere.

## Todo 📝

- [x] Create new component
- [x] Create storybook
- [x] Create new skeleton loader
- [ ] ~~Add to search results screen~~

## Inspiration 🌟

![Image](https://user-images.githubusercontent.com/41388783/214480564-2055c0f9-f689-4b2f-8448-0fd8adaaaff9.png)

**Comment by maxh1231** [comment]
@Thenlie wdym by new component? I'm imagining the ShowCard component visually looking like this. I must not understand.

**Comment by Thenlie** [comment]
@maxh1231 I mean make `ShowCardList` or something like that for this component. That way we can still use the current show card in places like the Discovery screen and in carousels.

Here is the relevant conversation.
![image](https://user-images.githubusercontent.com/41388783/216459586-95e82f9c-c1c1-4a8f-b03c-4296ea5a5e3d.png)

**Comment by Thenlie** [comment]
@jadenrapp I was thinking about picking up work on this ticket. Did you have a WIP branch here or would it be best to start from scratch?

**Comment by jadenrapp** [comment]
@Thenlie More than likely better to go from scratch. The changes I made for the two checked boxes was very minimal.

**Comment by Thenlie** [comment]
I have updated the acceptance criteria here as I think implementation should be considered another ticket entirely. We will have to re-think the search results page, and likely make a toggle between the card and list card. As such, this PR will mostly demo the component in storybook.

**Comment by Thenlie** [comment]
Closed by #435
